export const eventsData = [
    {
      id: 'evt-1',
      title: 'Latam Tour 2026',
      artist: 'Elena Pinderhughes',
      venue: 'La Media Torta',
      city: 'Bogotá',
      date: '2026-10-10T20:00:00',
      time: '20:00',
      price: 45000,
      capacity: 500,
      ticketsSold: 190,
      status: 'ON_SALE',
      imageUrl: '/images/elena.webp',
      isFeatured: true,
    },
    {
      id: 'evt-2',
      title: 'Latam Tour 2026',
      artist: 'Braxton Cook',
      venue: 'Teatro Colón',
      city: 'Bogotá',
      date: '2026-11-10T19:00:00',
      time: '19:00',
      price: 38000,
      capacity: 300,
      ticketsSold: 300,
      status: 'SOLD_OUT',
      imageUrl: '/images/braxton.webp',
    },
    {
      id: 'evt-3',
      title: 'Latam Tour 2026',
      artist: 'Louis Cole',
      venue: 'Parque de los Deseos',
      city: 'Medellín',
      date: '2026-12-11T21:00:00',
      time: '21:00',
      price: 55000,
      capacity: 400,
      ticketsSold: 120,
      status: 'ON_SALE',
      imageUrl: '/images/louis.jpg',
    },
    {
      id: 'evt-4',
      title: 'Latam Tour 2026',
      artist: 'Genevieve Artadi',
      venue: 'Centro Cultural del Café',
      city: 'Manizales',
      date: '2026-12-14T21:00:00',
      time: '21:00',
      price: 30000,
      capacity: 200,
      ticketsSold: 0,
      status: 'SCHEDULED',
      imageUrl: '/images/genevieve.jfif',
    },
    {
      id: 'evt-5',
      title: 'Latam Tour 2026',
      artist: 'Terrace Martin',
      venue: 'Bodega Comfama',
      city: 'Medellín',
      date: '2026-12-16T21:00:00',
      time: '21:00',
      price: 48000,
      capacity: 350,
      ticketsSold: 210,
      status: 'LIVE',
      imageUrl: '/images/terrace.jpg',
    },
    {
      id: 'evt-6',
      title: 'Latam Tour 2026',
      artist: 'Jazmin Sullivan',
      venue: 'Anfiteatro Los Cristales',
      city: 'Cali',
      date: '2026-12-22T21:00:00',
      time: '21:00',
      price: 52000,
      capacity: 450,
      ticketsSold: 450,
      status: 'FINISHED',
      imageUrl: '/images/jazmin.jfif',
    },
    {
      id: 'evt-7',
      title: 'Latam Tour 2026',
      artist: 'The Internet',
      venue: 'Teatro Principal',
      city: 'Pasto',
      date: '2026-12-23T21:00:00',
      time: '21:00',
      price: 40000,
      capacity: 280,
      ticketsSold: 40,
      status: 'CANCELED',
      imageUrl: '/images/internet.jfif',
    },
  ];