import { EventStatus, type Event } from '../src/models/events.js';

export const eventsData: Event[] = [
  {
    id: 'evt-1',
    title: 'Latam Tour 2026',
    artist: 'Elena Pinderhughes',
    venue: 'Teatro Municipal de Santiago',
    city: 'Santiago',
    date: new Date('2026-10-10T20:00:00'),
    time: '20:00',
    price: 45000,
    capacity: 500,
    ticketsSold: 190,
    status: EventStatus.ON_SALE,
    imageUrl: '/images/elena.webp',
    isFeatured: true,
  },
  {
    id: 'evt-2',
    title: 'Latam Tour 2026',
    artist: 'Elena Pinderhughes',
    venue: 'Teatro Municipal de Valparaíso',
    city: 'Valparaíso',
    date: new Date('2026-10-11T20:00:00'),
    time: '20:00',
    price: 42000,
    capacity: 400,
    ticketsSold: 120,
    status: EventStatus.ON_SALE,
    imageUrl: '/images/elena.webp',
  },
  {
    id: 'evt-3',
    title: 'Latam Tour 2026',
    artist: 'Braxton Cook',
    venue: 'Club Chocolate',
    city: 'Santiago',
    date: new Date('2026-11-10T21:00:00'),
    time: '21:00',
    price: 38000,
    capacity: 300,
    ticketsSold: 300,
    status: EventStatus.SOLD_OUT,
    imageUrl: '/images/braxton.webp',
  },
  {
    id: 'evt-4',
    title: 'Latam Tour 2026',
    artist: 'Braxton Cook',
    venue: 'Teatro Biobío',
    city: 'Concepción',
    date: new Date('2026-11-11T20:00:00'),
    time: '20:00',
    price: 34000,
    capacity: 350,
    ticketsSold: 0,
    status: EventStatus.SCHEDULED,
    imageUrl: '/images/braxton.webp',
  },
  {
    id: 'evt-5',
    title: 'Latam Tour 2026',
    artist: 'Louis Cole',
    venue: 'Teatro Caupolicán',
    city: 'Santiago',
    date: new Date('2026-12-11T21:00:00'),
    time: '21:00',
    price: 55000,
    capacity: 400,
    ticketsSold: 120,
    status: EventStatus.ON_SALE,
    imageUrl: '/images/louis.jpg',
  },
  {
    id: 'evt-6',
    title: 'Latam Tour 2026',
    artist: 'Louis Cole',
    venue: 'Teatro Cervantes',
    city: 'Valdivia',
    date: new Date('2026-12-12T19:00:00'),
    time: '19:00',
    price: 50000,
    capacity: 250,
    ticketsSold: 0,
    status: EventStatus.SCHEDULED,
    imageUrl: '/images/louis.jpg',
  },
  {
    id: 'evt-7',
    title: 'Latam Tour 2026',
    artist: 'Genevieve Artadi',
    venue: 'Teatro Biobío',
    city: 'Concepción',
    date: new Date('2026-12-14T21:00:00'),
    time: '21:00',
    price: 30000,
    capacity: 200,
    ticketsSold: 80,
    status: EventStatus.LIVE,
    imageUrl: '/images/genevieve.jfif',
  },
  {
    id: 'evt-8',
    title: 'Latam Tour 2026',
    artist: 'Terrace Martin',
    venue: 'Parque Cultural de Valparaíso',
    city: 'Valparaíso',
    date: new Date('2026-12-16T21:00:00'),
    time: '21:00',
    price: 48000,
    capacity: 350,
    ticketsSold: 210,
    status: EventStatus.ON_SALE,
    imageUrl: '/images/terrace.jpg',
  },
  {
    id: 'evt-9',
    title: 'Latam Tour 2026',
    artist: 'Jazmin Sullivan',
    venue: 'Movistar Arena',
    city: 'Santiago',
    date: new Date('2026-12-22T21:00:00'),
    time: '21:00',
    price: 52000,
    capacity: 450,
    ticketsSold: 450,
    status: EventStatus.FINISHED,
    imageUrl: '/images/jazmin.jfif',
  },
  {
    id: 'evt-10',
    title: 'Latam Tour 2026',
    artist: 'The Internet',
    venue: 'Teatro Cervantes',
    city: 'Valdivia',
    date: new Date('2026-12-23T21:00:00'),
    time: '21:00',
    price: 40000,
    capacity: 280,
    ticketsSold: 40,
    status: EventStatus.CANCELED,
    imageUrl: '/images/internet.jfif',
  },
  {
    id: 'evt-11',
    title: 'Latam Tour 2026',
    artist: 'The Internet',
    venue: 'Club Chocolate',
    city: 'Santiago',
    date: new Date('2027-01-12T20:30:00'),
    time: '20:30',
    price: 40000,
    capacity: 320,
    ticketsSold: 75,
    status: EventStatus.ON_SALE,
    imageUrl: '/images/internet.jfif',
  },
  {
    id: 'evt-12',
    title: 'Latam Tour 2026',
    artist: 'DOMi & JD Beck',
    venue: 'Sala SCD Bellavista',
    city: 'Santiago',
    date: new Date('2027-01-16T21:00:00'),
    time: '21:00',
    price: 38000,
    capacity: 300,
    ticketsSold: 0,
    status: EventStatus.SCHEDULED,
    imageUrl: '/images/placeholder.svg',
  },
  {
    id: 'evt-13',
    title: 'Latam Tour 2026',
    artist: 'Butcher Brown',
    venue: 'Teatro Coliseo',
    city: 'Valparaíso',
    date: new Date('2027-01-20T21:00:00'),
    time: '21:00',
    price: 35000,
    capacity: 350,
    ticketsSold: 25,
    status: EventStatus.SCHEDULED,
    imageUrl: '/images/placeholder.svg',
  },
];
